# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b5717c7f183afba127dfc8f734a7a93281efd9c2a9803be4239d738511d44b9c8a7dbb571c6b0b28411e318a7d3d425aedeefb4adf7794bce4e626b75916adf

test:
  secret_key_base: 085f3eefc4fb78776fe9bc2d558b007e65a7cc3d247319e0933eb8eddc237741e99af980abf37face00c8b96f9e1e25a9612632e0ce217e189748704d8d3e4ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
